services:
  api:
    build: .
    container_name: stockflow_api
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: bash -c "flask db upgrade && python create_admin.py && flask run --host=0.0.0.0"

  db:
    image: postgres:15
    container_name: stockflow_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
